server:
  port: 8080
spring:
  application:
    name: "countries"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://database-1.cacog5twnmdy.us-east-1.rds.amazonaws.com:5432/countries"
    username: "postgres"
    password: "postgres1234"
adapter:
  restconsumer:
    url: "https://restcountries.com/v3.1/all"
